// ============================================================
// Code Post-Processor
// ============================================================
// Parses code agent structured JSON output, validates files,
// and commits them to GitHub via GitHubMCP.
// ============================================================

import type { GitHubMCP }  from './github.js'
import type { MCPFile }    from './types.js'

interface CodeAgentOutput {
  summary:        string
  files:          MCPFile[]
  tests_command:  string
  notes:          string
}

const BLOCKED_PATHS = ['.env', '.env.local', 'secrets', 'credentials', 'node_modules']

export class CodePostProcessor {
  private github: GitHubMCP

  constructor(github: GitHubMCP) {
    this.github = github
  }

  async process(
    rawOutput:  string,
    sessionId:  string,
  ): Promise<{ committed: boolean; sha?: string; files: MCPFile[] }> {
    const parsed = this.parseOutput(rawOutput)
    if (!parsed || parsed.files.length === 0) {
      return { committed: false, files: [] }
    }

    const { valid, skipped } = this.validateFiles(parsed.files)
    if (skipped.length > 0) {
      console.log(JSON.stringify({ level: 'warn', event: 'files_skipped', skipped }))
    }
    if (valid.length === 0) {
      return { committed: false, files: parsed.files }
    }

    try {
      const result = await this.github.commitFiles(
        valid,
        `feat: ${parsed.summary}\n\nGenerated by Factorify code agent\nSession: ${sessionId}`,
        'develop',
      )

      console.log(JSON.stringify({
        level: 'info', event: 'code_committed',
        sha: result.sha, url: result.url,
        files: valid.map(f => f.path), session: sessionId,
      }))

      return { committed: true, sha: result.sha, files: valid }
    } catch (err) {
      console.error(JSON.stringify({
        level: 'error', event: 'commit_failed',
        error: (err as Error).message, session: sessionId,
      }))
      return { committed: false, files: valid }
    }
  }

  parseOutput(raw: string): CodeAgentOutput | null {
    // Strategy 1: direct JSON parse
    try {
      const clean = raw.replace(/```json\n?|```\n?/g, '').trim()
      const start = clean.indexOf('{')
      const end   = clean.lastIndexOf('}')
      if (start !== -1 && end !== -1) {
        const parsed = JSON.parse(clean.slice(start, end + 1)) as CodeAgentOutput
        if (this.isValidOutput(parsed)) return parsed
      }
    } catch { /* try next strategy */ }

    // Strategy 2: regex for JSON with files array
    try {
      const match = raw.match(/\{[\s\S]*"files"\s*:\s*\[[\s\S]*\][\s\S]*\}/)
      if (match) {
        const parsed = JSON.parse(match[0]) as CodeAgentOutput
        if (this.isValidOutput(parsed)) return parsed
      }
    } catch { /* give up */ }

    return null
  }

  private isValidOutput(parsed: CodeAgentOutput): boolean {
    return !!(
      parsed.files &&
      Array.isArray(parsed.files) &&
      parsed.files.length > 0 &&
      parsed.files.every(f =>
        typeof f.path === 'string' && f.path.length > 0 &&
        typeof f.content === 'string' && f.content.length > 10
      )
    )
  }

  private validateFiles(files: MCPFile[]): { valid: MCPFile[]; skipped: string[] } {
    const valid: MCPFile[] = []
    const skipped: string[] = []

    for (const file of files) {
      if (BLOCKED_PATHS.some(b => file.path.toLowerCase().includes(b))) {
        skipped.push(`${file.path} (blocked: sensitive path)`)
      } else if (file.path.startsWith('/') || file.path.includes('..')) {
        skipped.push(`${file.path} (blocked: absolute or traversal path)`)
      } else if (file.content.length < 10) {
        skipped.push(`${file.path} (skipped: empty content)`)
      } else {
        valid.push(file)
      }
    }

    return { valid, skipped }
  }
}
