// ============================================================
// Code Post-Processor
// ============================================================
// Parses code agent output and commits generated files to GitHub.
// Called after a successful code agent execution.
// ============================================================

import type { GitHubMCP }  from './github.js'
import type { MCPFile }    from './types.js'

interface CodeAgentOutput {
  summary:        string
  files:          MCPFile[]
  tests_command:  string
  notes:          string
}

export class CodePostProcessor {
  private github: GitHubMCP

  constructor(github: GitHubMCP) {
    this.github = github
  }

  async process(
    rawOutput:  string,
    sessionId:  string,
  ): Promise<{ committed: boolean; sha?: string; files: MCPFile[] }> {
    const parsed = this.parseOutput(rawOutput)
    if (!parsed || parsed.files.length === 0) {
      return { committed: false, files: [] }
    }

    try {
      const result = await this.github.commitFiles(
        parsed.files,
        `feat: ${parsed.summary}\n\nGenerated by Factorify code agent\nSession: ${sessionId}`,
        'develop',
      )

      console.log(JSON.stringify({
        level:   'info',
        event:   'code_committed',
        sha:     result.sha,
        url:     result.url,
        files:   parsed.files.map(f => f.path),
        session: sessionId,
      }))

      return { committed: true, sha: result.sha, files: parsed.files }
    } catch (err) {
      console.error(JSON.stringify({
        level:   'error',
        event:   'commit_failed',
        error:   (err as Error).message,
        session: sessionId,
      }))
      return { committed: false, files: parsed.files }
    }
  }

  parseOutput(raw: string): CodeAgentOutput | null {
    try {
      const clean = raw.replace(/```json\n?|```\n?/g, '').trim()
      const start = clean.indexOf('{')
      const end   = clean.lastIndexOf('}')
      if (start === -1 || end === -1) return null
      return JSON.parse(clean.slice(start, end + 1)) as CodeAgentOutput
    } catch {
      return null
    }
  }
}
