// ============================================================
// Error Pattern Detector
// ============================================================
// Monitors learning occurrences and triggers spec update
// proposals when the same error pattern appears 3+ times.
// Creates a GitHub PR with the proposed spec update.
// ============================================================

import type { GitHubMCP } from '@factory/mcp-servers'

export class ErrorPatternDetector {
  private github: GitHubMCP
  private owner:  string
  private repo:   string

  constructor(github: GitHubMCP, owner = 'marckrs', repo = 'factorify') {
    this.github = github
    this.owner  = owner
    this.repo   = repo
  }

  async checkAndPropose(
    agent:       string,
    patternKey:  string,
    occurrences: number,
    description: string,
    proposedFix: string,
  ): Promise<{ proposed: boolean; pr_url?: string }> {
    // Only act at exactly 3 occurrences to avoid duplicate PRs
    if (occurrences !== 3) return { proposed: false }

    console.log(JSON.stringify({
      level:   'warn',
      event:   'error_pattern_threshold_reached',
      agent,
      pattern: patternKey,
      count:   occurrences,
    }))

    try {
      const specPath    = this.getSpecPath(agent)
      const currentSpec = await this.github.readFile(specPath) ?? ''
      const timestamp   = new Date().toISOString().slice(0, 10)
      const branchId    = Math.random().toString(36).slice(2, 6)
      const prBranch    = `fix/learning-${agent}-${timestamp}-${branchId}`

      const addendum = [
        ``,
        `## Aprendizados automaticos (gerado em ${timestamp})`,
        ``,
        `### Padrao detectado: ${patternKey}`,
        `Ocorrencias: ${occurrences}`,
        ``,
        `**Problema:** ${description}`,
        ``,
        `**Correcao proposta:** ${proposedFix}`,
      ].join('\n')

      await this.github.upsertFile(
        { path: specPath, content: currentSpec + addendum },
        `fix(${agent}): add learning from ${occurrences} error occurrences`,
        prBranch,
      )

      const prRes = await fetch(
        `https://api.github.com/repos/${this.owner}/${this.repo}/pulls`,
        {
          method:  'POST',
          headers: {
            Authorization:  `Bearer ${process.env.GITHUB_TOKEN}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            title: `[Learning] Update ${agent} spec — pattern detected ${occurrences}x`,
            body:  [
              `## Automatic spec update proposal`,
              ``,
              `The **${agent}** agent encountered the same error pattern **${occurrences} times**.`,
              ``,
              `**Pattern:** \`${patternKey}\``,
              `**Description:** ${description}`,
              `**Proposed fix:** ${proposedFix}`,
              ``,
              `---`,
              `*Generated by Factorify Learning Layer (Sprint 4)*`,
            ].join('\n'),
            head: prBranch,
            base: 'main',
          }),
        }
      )

      const pr = await prRes.json() as { html_url: string }

      console.log(JSON.stringify({
        level:  'info',
        event:  'spec_update_pr_created',
        agent,
        pr_url: pr.html_url,
      }))

      return { proposed: true, pr_url: pr.html_url }
    } catch (err) {
      console.error(JSON.stringify({
        level: 'error',
        event: 'spec_update_failed',
        agent,
        error: (err as Error).message,
      }))
      return { proposed: false }
    }
  }

  private getSpecPath(agent: string): string {
    const map: Record<string, string> = {
      'code-smith':     'agents/dev/code/spec.md',
      'test-engineer':  'agents/dev/test/spec.md',
      'review-guard':   'agents/dev/review/spec.md',
      'infra-pilot':    'agents/ops/deploy/spec.md',
      'monitor':        'agents/ops/monitor/spec.md',
      'incident':       'agents/ops/incident/spec.md',
      'gtm':            'agents/biz/gtm/spec.md',
      'biz-analyst':    'agents/biz/analytics/spec.md',
      'support':        'agents/biz/support/spec.md',
    }
    return map[agent] ?? `agents/unknown/${agent}/spec.md`
  }
}
